### ISSUE TITLE
Release Update for Firefox More Often

### ISSUE THREAD

**Issue by magnus-staberg** [lusakasa/saka-key#2]
Thanks for the awesome webextension.

Would you mind updating the app on Firefox's addon market more often?

**Comment by eejdoowad** [comment]
Thanks for the feedback. The next release will be published on Firefox and I'll  start posting Firefox releases together with chrome releases.

**Comment by eejdoowad** [comment]
Hi @magnus-staberg. I've just released version 1.11 and published it on chrome and firefox. The turn around time for firefox addons approval is usually long (multiple days to weeks). 

Until then, try building Saka Key from version 1.11's commit (https://github.com/lusakasa/saka-key/commit/85e42905c059a212d2c22861e008af903b72e050) by following the instructions in the readme (npm install && npm run build:prod:firefox).

**Comment by magnus-staberg** [comment]
Great, thanks :)

I tried building and installing but can't figure out how to install it on Firefox. Firefox wanted a add-on file format but I found none in dist folder.

In firefox I open about:addons and then "Install add-on From File". Is this not the way to install it?
<img width="545" alt="screen shot 2017-06-27 at 11 51 25" src="https://user-images.githubusercontent.com/921390/27581800-fd92cd5c-5b2e-11e7-86bc-f43ee3b2eb53.png">

**Comment by eejdoowad** [comment]
Currently, the easiest way is to navigate to [about:debugging](about:debugging), click _Load Temporary Add-on_, select any file within the generated _dist_ directory, and hit open.

Extensions loaded this way will automatically be removed when you close the browser.

**Comment by eejdoowad** [comment]
Firefox isn't my daily driver, so if you experience any difficulties please let me know.

Firefox bugs I know about:
* Scrolling the options GUI in the popup is broken... so you're better off opening the options GUI in a new tab.
* Only opening links the standard way works. You can't, for example, open links in a background tab.

**Comment by magnus-staberg** [comment]
I installed the locally built version, commit 85e4290, but cannot open the settings. the window clicking on the icon is empty and clicking options on info.html resolves to an empty page.

<img width="224" alt="screen shot 2017-06-27 at 20 20 32" src="https://user-images.githubusercontent.com/921390/27603452-6ebd17b6-5b76-11e7-8ef1-8904d80bea4e.png">
<img width="606" alt="screen shot 2017-06-27 at 20 20 39" src="https://user-images.githubusercontent.com/921390/27603456-749e53ac-5b76-11e7-9dc8-4a4bd12306c4.png">

**Comment by eejdoowad** [comment]
From my experience, that happens when you generate a chrome build by running **npm run build** instead of **npm run build:firefox**. Even after you load in the extension, make sure not to run **npm run build** because firefox uses whatever files exist in the dist directory.

**Comment by magnus-staberg** [comment]
I did `npm run build:prod:firefox` but retried with `npm run build:firefox` and that seems to be working better.

**Comment by eejdoowad** [comment]
That's strange. I'll look into it.

**Comment by magnus-staberg** [comment]
I've activated `Prevent Pages From Stealing Focus`. On google it works for the first tapped key but the following keys will be insterted into the search input.

**Comment by eejdoowad** [comment]
It doesn't seem to work for me at all on google searches. It works fine on google.com

**Comment by eejdoowad** [comment]
I think the 'Prevent Pages From Stealing Focus' issue, and many others relating to DOM event handling, have been resolved in version 1.14 (the latest commit).

**Comment by eejdoowad** [comment]
I haven't been able to replicate your issue with loading production builds. I tried a fresh Ubuntu virtual machine with Firefox Developer Edition. Saka Key requires a recent version of Firefox. I advise using Firefox Developer addition.

**Comment by magnus-staberg** [comment]
With google searches I meant searching on google.com
google.com is working a lot better in latest commit.

I checked out latest commit and successfully built `npm run build:prod:firefox`.

**Comment by eejdoowad** [comment]
Great! I made some major architectural changes that should let the Firefox build work much reliably.

**Comment by gliptak** [comment]
https://addons.mozilla.org/en-US/firefox/addon/saka-key/ still shows version 1.3

If it is very time consuming keep Firefox up-to-date, could you consider offering "release" files (directly in the project)?

Thanks

**Comment by eejdoowad** [comment]
I apologize for the extended wait for Firefox updates. I submitted an update over a month ago and it's still sitting at 5 of 159 in the approval queue.

Hosting release files is an extra step in the development process that will slow it down (unless I spend time automating it). I figure my users are either: 1) developers who will have no problem following the build instructions in the readme, or 2) general users who won't get further than the firefox marketplace.

It's something l should do eventually, but there are so many other features and fixes I want to implement. Meanwhile, I take care to ensure the master branch always contains a working build. So `git pull origin master && npm run:build:prod` should always get you the latest release.

**Comment by gliptak** [comment]
@eejdoowad No need to apologize for somebody else's slow review queue.

**Comment by IGI-111** [comment]
Have you considered using the beta extension channel for intermediate releases? It doesn't have the approval constrainst and it would still allow for people to get the latest version from the marketplace to test.

**Comment by eejdoowad** [comment]
@IGI-111 thanks! I had no idea beta channels existed. Firefox users, the beta channel now hosts version 1.18.0. Enjoy!

**Comment by gliptak** [comment]
The beta channel direct link for current version is https://addons.mozilla.org/firefox/downloads/latest-beta/saka-key/addon-795406-latest.xpi?src=dp-btn-devchannel

Consider closing this issue.
